# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SmartMobeTest' do
    use_frameworks!
 pod 'Alamofire'
 pod 'ReachabilitySwift'
 pod 'SwiftyJSON'
 pod 'TTGSnackbar'
 pod 'SDWebImage'
 pod 'IQKeyboardManagerSwift'

end
